version: '3.8'

services:
  scraper:
    build:
      context: .
      dockerfile: tasks/scraper/Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/database

  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - data:/var/lib/postgresql/data

  visualization:
    build:
      context: .
      dockerfile: tasks/visualization/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/database

  # notebook:
  #   image: jupyter/scipy-notebook
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - data:/notebook
  #   depends_on:
  #     - db
  #   environment:
  #     - JUPYTER_TOKEN=mysecretpassword
  #     - DATABASE_URL=postgresql://user:password@db:5432/database


volumes:
  data:
